/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface OgFeaturesPage {
    }
    interface OgLandingPage {
    }
    interface OgLogo {
        "animated": boolean;
    }
    interface OgNotFoundPage {
    }
    interface OgPrivacyPolicyPage {
    }
    interface OgTermsPage {
    }
    interface OgVideoModal {
        "modal": HTMLIonModalElement;
        "videoURL": string;
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLOgFeaturesPageElement extends Components.OgFeaturesPage, HTMLStencilElement {
    }
    var HTMLOgFeaturesPageElement: {
        prototype: HTMLOgFeaturesPageElement;
        new (): HTMLOgFeaturesPageElement;
    };
    interface HTMLOgLandingPageElement extends Components.OgLandingPage, HTMLStencilElement {
    }
    var HTMLOgLandingPageElement: {
        prototype: HTMLOgLandingPageElement;
        new (): HTMLOgLandingPageElement;
    };
    interface HTMLOgLogoElement extends Components.OgLogo, HTMLStencilElement {
    }
    var HTMLOgLogoElement: {
        prototype: HTMLOgLogoElement;
        new (): HTMLOgLogoElement;
    };
    interface HTMLOgNotFoundPageElement extends Components.OgNotFoundPage, HTMLStencilElement {
    }
    var HTMLOgNotFoundPageElement: {
        prototype: HTMLOgNotFoundPageElement;
        new (): HTMLOgNotFoundPageElement;
    };
    interface HTMLOgPrivacyPolicyPageElement extends Components.OgPrivacyPolicyPage, HTMLStencilElement {
    }
    var HTMLOgPrivacyPolicyPageElement: {
        prototype: HTMLOgPrivacyPolicyPageElement;
        new (): HTMLOgPrivacyPolicyPageElement;
    };
    interface HTMLOgTermsPageElement extends Components.OgTermsPage, HTMLStencilElement {
    }
    var HTMLOgTermsPageElement: {
        prototype: HTMLOgTermsPageElement;
        new (): HTMLOgTermsPageElement;
    };
    interface HTMLOgVideoModalElement extends Components.OgVideoModal, HTMLStencilElement {
    }
    var HTMLOgVideoModalElement: {
        prototype: HTMLOgVideoModalElement;
        new (): HTMLOgVideoModalElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "og-features-page": HTMLOgFeaturesPageElement;
        "og-landing-page": HTMLOgLandingPageElement;
        "og-logo": HTMLOgLogoElement;
        "og-not-found-page": HTMLOgNotFoundPageElement;
        "og-privacy-policy-page": HTMLOgPrivacyPolicyPageElement;
        "og-terms-page": HTMLOgTermsPageElement;
        "og-video-modal": HTMLOgVideoModalElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface OgFeaturesPage {
    }
    interface OgLandingPage {
    }
    interface OgLogo {
        "animated"?: boolean;
    }
    interface OgNotFoundPage {
    }
    interface OgPrivacyPolicyPage {
    }
    interface OgTermsPage {
    }
    interface OgVideoModal {
        "modal"?: HTMLIonModalElement;
        "videoURL"?: string;
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "og-features-page": OgFeaturesPage;
        "og-landing-page": OgLandingPage;
        "og-logo": OgLogo;
        "og-not-found-page": OgNotFoundPage;
        "og-privacy-policy-page": OgPrivacyPolicyPage;
        "og-terms-page": OgTermsPage;
        "og-video-modal": OgVideoModal;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "og-features-page": LocalJSX.OgFeaturesPage & JSXBase.HTMLAttributes<HTMLOgFeaturesPageElement>;
            "og-landing-page": LocalJSX.OgLandingPage & JSXBase.HTMLAttributes<HTMLOgLandingPageElement>;
            "og-logo": LocalJSX.OgLogo & JSXBase.HTMLAttributes<HTMLOgLogoElement>;
            "og-not-found-page": LocalJSX.OgNotFoundPage & JSXBase.HTMLAttributes<HTMLOgNotFoundPageElement>;
            "og-privacy-policy-page": LocalJSX.OgPrivacyPolicyPage & JSXBase.HTMLAttributes<HTMLOgPrivacyPolicyPageElement>;
            "og-terms-page": LocalJSX.OgTermsPage & JSXBase.HTMLAttributes<HTMLOgTermsPageElement>;
            "og-video-modal": LocalJSX.OgVideoModal & JSXBase.HTMLAttributes<HTMLOgVideoModalElement>;
        }
    }
}
